services:
  backend:
    build: ./backend
    container_name: progress-app
    command: flask run --host=0.0.0.0 --port=5000
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    env_file:
      - ./backend/.env.dev
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    container_name: progress-db
    restart: always
    env_file:
      - ./backend/.env.dev
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    container_name: progress-redis

  celery_worker:
    build: ./backend
    container_name: progress-celery-worker
    command: celery -A app.celery_app.celery worker --loglevel=info
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
    env_file:
      - ./backend/.env.dev
    depends_on:
      - db
      - redis

  celery_beat:
    build: ./backend
    container_name: progress-celery-beat
    command: celery -A app.celery_app.celery beat --loglevel=info
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
    env_file:
      - ./backend/.env.dev
    depends_on:
      - db
      - redis
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP

  frontend:
    build: ./frontend
    container_name: progress-frontend
    profiles:
      - frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - DOCKER=true
    depends_on:
      - backend
volumes:
  db_data:
