services:
  backend:
    build: ./backend
    command: flask run --host=0.0.0.0 --port=5000
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=production
    env_file:
      - ./backend/.env.prod
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    restart: always

  celery_worker:
    build: ./backend
    command: celery -A app.celery_app.celery worker -Q progress_mail -n
      progress_mail@%h -c 2 -l info
    env_file:
      - ./backend/.env.prod

  celery_beat:
    build: ./backend
    command: celery -A app.celery_app.celery beat --loglevel=info
    env_file:
      - ./backend/.env.prod
