"""add task access group support

Revision ID: 47960a18b35a
Revises: 96aa691c2270
Create Date: 2026-05-04 09:17:42.276389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47960a18b35a'
down_revision = '96aa691c2270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_subject',
    sa.Column('subject_type', sa.Integer(), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_type', 'ref_id', name='uq_subject_type_ref_id')
    )
    op.create_table('group',
    sa.Column('name', sa.String(255), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('scope_type', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_member',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_access',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('access_level', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['access_subject.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'subject_id', name='uq_task_subject')
    )
    with op.batch_alter_table('objective_reminder_logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('objective_reminder_logs_ibfk_3'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('objective_reminder_logs_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'objective', ['objective_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('objective_reminder_settings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('objective_reminder_settings_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'objective', ['objective_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('task_access_organization', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('task_access_organization_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('task_access_organization_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'task', ['task_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'organization', ['organization_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('task_access_user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('task_access_user_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'task', ['task_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_task_order', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_task_order_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'task', ['task_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_task_order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_task_order_ibfk_1'), 'task', ['task_id'], ['id'])

    with op.batch_alter_table('task_access_user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('task_access_user_ibfk_1'), 'task', ['task_id'], ['id'])

    with op.batch_alter_table('task_access_organization', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('task_access_organization_ibfk_1'), 'organization', ['organization_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('task_access_organization_ibfk_2'), 'task', ['task_id'], ['id'])

    with op.batch_alter_table('objective_reminder_settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('objective_reminder_settings_ibfk_1'), 'objective', ['objective_id'], ['id'])

    with op.batch_alter_table('objective_reminder_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('objective_reminder_logs_ibfk_1'), 'objective', ['objective_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('objective_reminder_logs_ibfk_3'), 'user', ['user_id'], ['id'])

    op.drop_table('task_access')
    op.drop_table('group_member')
    op.drop_table('group')
    op.drop_table('access_subject')
    # ### end Alembic commands ###
