"""sync with current models

Revision ID: 96aa691c2270
Revises: c4e4d509568e
Create Date: 2026-04-20 20:55:08.201529

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96aa691c2270'
down_revision = 'c4e4d509568e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objective', schema=None) as batch_op:
        batch_op.alter_column('display_order',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)

    with op.batch_alter_table('objective_reminder_settings', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.alter_column('level',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('progress_update', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_superuser',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_user_password_reset_expires_at'))
        batch_op.drop_index(batch_op.f('ix_user_password_reset_token_hash'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_password_reset_token_hash'), ['password_reset_token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_password_reset_expires_at'), ['password_reset_expires_at'], unique=False)
        batch_op.alter_column('is_superuser',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)

    with op.batch_alter_table('progress_update', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.alter_column('level',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('objective_reminder_settings', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)

    with op.batch_alter_table('objective', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('display_order',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
