"""Add soft delete to Userand Organization models

Revision ID: c4e4d509568e
Revises: 5f1a3a3ee19c
Create Date: 2025-09-05 17:36:59.213584

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c4e4d509568e'
down_revision = '5f1a3a3ee19c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objective', schema=None) as batch_op:
        batch_op.alter_column('task_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('progress_update', schema=None) as batch_op:
        batch_op.alter_column('objective_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('task_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('assigned_user_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False))
        batch_op.drop_index(batch_op.f('wp_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_normalized_email'))
        batch_op.create_index(batch_op.f('ix_user_normalized_email'), ['normalized_email'], unique=False)
        batch_op.create_unique_constraint('uq_user_email_active', ['normalized_email', 'is_deleted'])
        batch_op.create_unique_constraint('uq_user_wp_id_active', ['wp_user_id', 'is_deleted'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_wp_id_active', type_='unique')
        batch_op.drop_constraint('uq_user_email_active', type_='unique')
        batch_op.drop_index(batch_op.f('ix_user_normalized_email'))
        batch_op.create_index(batch_op.f('ix_user_normalized_email'), ['normalized_email'], unique=True)
        batch_op.create_index(batch_op.f('wp_user_id'), ['wp_user_id'], unique=True)
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('task_ibfk_1'), 'user', ['assigned_user_id'], ['id'])

    with op.batch_alter_table('progress_update', schema=None) as batch_op:
        batch_op.alter_column('objective_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('objective', schema=None) as batch_op:
        batch_op.alter_column('task_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
