name: Frontend Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ---------------------------
      # Checkout
      # ---------------------------
      - name: Checkout
        uses: actions/checkout@v4

      # ---------------------------
      # Node
      # ---------------------------
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # ---------------------------
      # Install
      # ---------------------------
      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      # ---------------------------
      # Generate API
      # ---------------------------
      - name: Generate API
        working-directory: frontend
        run: npm run generate:api
        env:
          VITE_OPENAPI_URL: https://api.anzai-home.com/progress-dev/api/doc/openapi.json

      # ---------------------------
      # Build
      # ---------------------------
      - name: Build frontend
        working-directory: frontend
        run: npm run build

      # ---------------------------
      # Upload dist
      # ---------------------------
      - name: Upload dist
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}

          source: "frontend/dist/*"
          target: "/home/taro/task-progress-docker/"

      # ---------------------------
      # Restart frontend container
      # ---------------------------
      - name: Restart frontend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}

          script: |
            cd ~/task-progress-docker
            docker compose -f docker-compose.prod.yml restart frontend